services:
  main:
    build:
      args:
        - uis=${UID}
        - userName=${USERNAME}
        - password=${PASSWORD}
        - gid=${GID}
        - groupName=${GROUPNAME}
        - gitUserName=${GIT_USERNAME}
        - gitUserEmail=${GIT_USEREMAIL}
      context: .
    ports:
      - "$PORT"
      - "$STORYBOOK_PORT"
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: projects
        target: /home/$USERNAME/projects/
volumes:
  projects:
